### ISSUE TITLE
[REQ] auto with to obsidian-recipe-view for specific file name string or YAML property

### ISSUE THREAD

**Issue by zeltak** [lachholden/obsidian-recipe-view#19] opened 2024-02-11 02:58 UTC
Hi and thx so much for your amazing work!!!

been really enjoying using obsidian-recipe-view and even reformatted my 1500 recipes (phew!) to match obsidian-recipe-view suggested format!

I keep all my markdown files in 1 vault, and it gets a bit tedious each time I open a recipe file to issue the command to toggle to obsidian-recipe-view :)

I was wondering if you would consider to auto trigger the view switch based on a specific file name string or YAML property?

ie if the file has the string `food.cook` in it or the YAML tag has `food` etc

thx so much for considering :) 

Z

**Comment by lachholden** [comment] 2024-02-14 10:36
Yes this is definitely something I'm keen to add! Life has been super busy lately, but when I get the chance to work on it again this will be one of the first things :)


Closing as duplicate of #4

**Closed by lachholden** 2024-02-14 10:36 UTC
Labels: duplicate
